### PR TITLE
Removes code smells

### PR DESCRIPTION
**Pull request by pruthvi2103**
## Description

Removes code smells reported by sonar

### CODE REVIEW

**Comment by saurabhsutar192** [comment]
Tooltip and Popover will have duplications...because the tooltip is based on the popover component....but we decided to keep them separate.

**Comment by Raalzz** [comment]
> Tooltip and Popover will have duplications...because the tooltip is based on the popover component....but we decided to keep them separate.

Is there a way, That we can abstract duplicated code and reuse it wherever needed?

**Comment by saurabhsutar192** [comment]
> > Tooltip and Popover will have duplications...because the tooltip is based on the popover component....but we decided to keep them separate.
> 
> Is there a way, That we can abstract duplicated code and reuse it wherever needed?

Have to look into it and see what I can do..

**Comment by saurabhsutar192** [comment]
LGTM!

**Pull request merged**
